name: Docker CI/CD Pipeline
on:
  push:
    branches:
      - jaiye/gitaction-s3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JAIYE_USERNAME }}
          password: ${{ secrets.JAIYE_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kingjaiye/ben10:latest
      - name: Login to the EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.JAIYE_HOST }}
            username: ${{ secrets.VICTOR_USERNAME }}
            key: ${{ secrets.JAIYE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker stop ben10 || true
              docker rm ben10 || true
              docker pull ${{ secrets.JAIYE_USERNAME }}/ben10:lastest
              docker run -d --name ben10 -p 80:80 ${{ secrets.JAIYE_USERNAME }}/ben10:lastest
              