name: CI/CD Pipeline and AWS Balancer
on:
  push:
    branches:
      - jaiye/gitaction-s3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Workflow ID as Environment Variable
        run: echo "WORKFLOW_ID=${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to the EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.JAIYE_HOST }}
            username: ${{ secrets.VICTOR_USERNAME }}
            key: ${{ secrets.JAIYE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              echo "WORKFLOW_ID=${{ github.run_id }}" | sudo tee -a /etc/environment
              source /etc/environment
              cd ben10
              git pull origin jaiye/gitaction-s3
              docker compose up --detach --build
