name: Docker CI/CD Pipeline and AWS Balancer
on:
  push:
    branches:
      - jaiye/gitaction-s3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to the EC2s
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.JAIYE_HOST }}
            username: ${{ secrets.VICTOR_USERNAME }}
            key: ${{ secrets.JAIYE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              cd ben10
              git pull origin jaiye/gitaction-s3
              docker compose up --detach --build
              