name: Docker CI/CD Pipeline and AWS Balancer
on:
  push:
    branches:
      - jaiye/gitaction-s3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JAIYE_USERNAME }}
          password: ${{ secrets.JAIYE_PASSWORD }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          file: ben10file
          context: .
          push: true
          tags: kingjaiye/ben10:${{ github.run_id }}
      - name: Login to the EC2s
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.JAIYE_HOST }}
            username: ${{ secrets.VICTOR_USERNAME }}
            key: ${{ secrets.JAIYE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker compose pull kingjaiye/ben10:${{ github.run_id }}
              docker compose up
              