name: Deploy Ben10 future Microservice
on:
  push:
    branches:
      - taiwo/ben10


jobs:
  build:
    name: Build Ben10 Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEEWAI_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEEWAI_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Ben10 ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ben10-account
      run: |
        echo "$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}

  pilot-deploy:
    name: Deploy Ben10 to dev
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/taiwo/ben10'
    env:
      ECR_REPOSITORY: ben10-account
      DIRECTORY: account
      COMPOSE: docker-compose.yml
      ECR_REGISTRY: ${{vars.ECR_REGISTRY}}
    steps:
    - name: ssh login to Ben10 EC2 Instance
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.TEEWAI_HOST }}
        username: ${{ secrets.TEEWAI_USERNAME }}
        key: ${{ secrets.TEEWAI_KEY }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_TRIGGERING_ACTOR,GITHUB_RUN_NUMBER,ECR_REGISTRY,ECR_REPOSITORY,DIRECTORY,COMPOSE
        script: |
          echo  "$GITHUB_TRIGGERING_ACTOR -Deployment Initiated- \nPulling build artifact $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
          cd $DIRECTORY && yq '.services.account-service.image = "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_RUN_NUMBER}"' -i  $COMPOSE && \
          docker-compose up --build --force-recreate -d
          if [[ $? == 0 ]]; then
            echo "Deployment Successful!!!"
            else
              echo "Error!!!!! can not recreate service update"
              exit 1
          fi