name: CI/CD Pipeline and AWS Balancer
on:
  push:
    branches:
      - taiwo/ben10
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull teewaidock/ben10:latest

      - name: Login to the EC2s
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.TEEWAI_HOST }}
            username: ${{ secrets.TEEWAI_USERNAME }}
            key: ${{ secrets.TEEWAI_KEY }}
            port: ${{ secrets.PORT }}
            script: | 
              sudo apt update     
              docker stop ben10
              docker pull teewaidock/ben10:latest
              docker run -d -p 80:80 teewaidock/ben10:latest