name: CI/CD Pipeline and AWS Balancer
on:
  push:
    branches:
      - taiwo/ben10
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to the EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.TEEWAI_HOST }}
            username: ${{ secrets.TEEWAI_USERNAME }}
            key: ${{ secrets.TEEWAI_KEY }}
            port: ${{ secrets.PORT }}
            script: |        
              cd ben10
              git pull origin taiwo/ben10
              docker compose up -d --build